name: ADFARMDeploy
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
# Installs Node and the npm packages saved in your package.json file in the build
